### ISSUE TITLE
Bug: Splunk HEC rejecting ingestion due to invalid keys "reingest" and "frombucket" in event metadata

### ISSUE THREAD

**Issue by SidMallya** [pauld-splunk/aws-splunk-firehose-error-reingest#1]
I have tested the whole setup of firehose-reingest option in 2 different environments.  In both cases the events are failing to reach Splunk.  The error message is: "The data is not formatted correctly.....".  This needs to be fixed urgently otherwise the aws-splunk-firehose-error-reingest/firehose-reingest option won't work.

The event metadata sent to Splunk HEC contains 2 additional keys "reingest" and "frombucket" which is causing the problem.  These additional fields are causing the Splunk HEC to reject the event.

cURL command including keys "reingest" and "frombucket" fails:
```
[ec2-user@ip-xxx-xx-xx-xx ~]$ curl -k -H "Authorization: Splunk <Authentication token>" http://xx.xxx.xx.xxx:8088/services/collector/event -d '{"sourcetype": "test-sourcetype", "source": "aws:firehose", "event": "This is a test event", "reingest": "reingest:1", "frombucket": "test-bucket"}'
{"text":"No data","code":5}
```
cURL command excluding keys "reingest" and "frombucket" succeeds:
```
[ec2-user@ip-xxx-xx-xx-xx ~]$ curl -k -H "Authorization: Splunk <Authentication token>" http://xx.xxx.xx.xxx:8088/services/collector/event -d '{"sourcetype": "test-sourcetype", "source": "aws:firehose", "event": "This is a test event"}'
{"text":"Success","code":0}
```

I ran a simple test to confirm this.  I removed the below lines from aws-splunk-firehose-error-reingest/firehose-reingest/kinesis_lambda_function.py and the events are getting written to Splunk index successfully.

```
        if data.get('reingest')!=None:
            return_event['reingest'] = data['reingest']
        if data.get('frombucket')!=None:
            return_event['frombucket'] = data['frombucket']
```

Removing these lines is not the solution as:
1) The function will go to an infinite loop if the ingestion to Splunk fails
2) The reingest key is used to store the number of time the reingest has happened and frombucket key is used to store the S3 bucket from which the event data has been fetched.

A solution is needed that does not send these keys in the event metadata to Splunk but passes these values to the next iteration in case of a failed delivery to Splunk through any other means.

**Comment by pauld-splunk** [comment]
@SidMallya - can you confirm that you are using the Event endpoint for HEC with your firehose vs Raw

**Comment by SidMallya** [comment]
@pauld-splunk - I confirm that I am using the Event endpoint for HEC with my firehose.

**Comment by pauld-splunk** [comment]
@SidMallya updated and fixed

**Comment by SidMallya** [comment]
@pauld-splunk Thanks!
